title: Hirotaka Ogawa
#description: > # this means to ignore newlines until "baseurl:"
#  A researcher going back and forth between Odaiba, Tsukuba, and Ookayama, Japan. The views expressed here are mine alone and not those of my employer.
description: > # this means to ignore newlines until "baseurl:"
  A researcher serving as a temporary bureaucrat. The views expressed here are mine alone and not those of my employer.
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://ogawa.github.io" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Hirotaka Ogawa # add your name
author-img: hirotaka-ogawa.jpg # add your photo
about-author: A researcher serving as a temporary bureaucrat. The views expressed here are mine alone and not those of my employer.
social-twitter: ogawa # add your Twitter handle
social-facebook: hirotaka.ogawa # add your Facebook handle
social-github: ogawa # add your Github handle
social-linkedin: hogawa # add your Linkedin handle
social-email: # add your Email address

# Disqus
discus-identifier: # add your discus identifier

# Tracker
analytics: UA-122585620-1 # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
